# Generated by Django 3.2.9 on 2022-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0002_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
