# Generated by Django 3.2.9 on 2022-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0004_categories_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='product_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='static/categoryimg'),
        ),
    ]
