# Generated by Django 3.2.9 on 2022-11-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0005_auto_20221114_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Addcategorie',
        ),
    ]
