# Generated by Django 3.2.9 on 2022-11-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0008_auto_20221116_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcategorie',
            old_name='product_img',
            new_name='product_image',
        ),
    ]
