# Generated by Django 3.2.9 on 2022-11-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0009_rename_product_img_addcategorie_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcategorie',
            old_name='product_date',
            new_name='categ_date',
        ),
        migrations.RenameField(
            model_name='addcategorie',
            old_name='product_image',
            new_name='categ_image',
        ),
        migrations.RenameField(
            model_name='addcategorie',
            old_name='product_name',
            new_name='categ_name',
        ),
    ]
