# Generated by Django 3.2.9 on 2022-11-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0010_auto_20221116_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=100)),
                ('offsell_price', models.FloatField()),
                ('offdisct_price', models.FloatField()),
                ('offprod_avail', models.FloatField(default=500)),
                ('offbrand', models.CharField(max_length=100)),
                ('offprod_img', models.ImageField(blank=True, upload_to='static/productimg')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_descp',
        ),
    ]
