# Generated by Django 3.2.9 on 2022-11-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0013_auto_20221117_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addcategorie',
        ),
        migrations.DeleteModel(
            name='bestoffer',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AC', 'All Category'), ('TSP', 'Top Savers Today'), ('BO', 'Best Offer')], max_length=20, null=True),
        ),
    ]
