# Generated by Django 3.2.9 on 2022-11-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0014_auto_20221117_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
