# Generated by Django 3.2.9 on 2022-11-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0015_product_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TSP', 'Top Savers Today'), ('BO', 'Best Offer'), ('FV', 'Fruits & Vegetables'), ('GS', 'Grocery & Staples'), ('BV', 'Beverages'), ('BD', 'Breakfast & Dairy'), ('BSC', 'Biscuits, Snacks & Chocolates'), ('NSI', 'Noodles, Sauces & Instant Food'), ('MFS', 'Meats, Frozen & Seafood')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='media/static/productimg'),
        ),
    ]
