# Generated by Django 3.2.9 on 2022-11-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehome', '0016_auto_20221124_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='static/productimg'),
        ),
    ]
